### ISSUE TITLE
Master Issue for Drawing/Display Problems

### ISSUE THREAD

**Issue by aogden41** [gander-oceanic-fir-vatsim/vatsim-NAAATS#12]
- [ ] Scale menu bar for lower screen resolutions
- [x] All lines should be 2px and anti-aliased
- [x] Text display issue on the drawing of conflict tools
- [ ] Scroll bar a bit jittery

**Comment by aogden41** [comment]
no longer relevant
